import type { ReactNode } from "react";
import { CopyButton } from "@/components/chat/CopyButton";
import type { TechnicalTrace } from "@/types/chat";

/**
 * Mirrors apps/api/src/ai/prompts/intent.ts - short, human descriptions of
 * the 10 approved intents, for display only (never used to decide
 * behavior; the backend already decided the intent before this renders).
 */
const INTENT_DESCRIPTIONS: Record<string, string> = {
  transaction_spend_total: "Total debit (spend) amount, optionally scoped by bank/program/date range.",
  transaction_income_total: "Total credit (income) amount, optionally scoped by bank/program/date range.",
  transaction_count: "Count of transactions, optionally filtered by type/bank/date range.",
  transaction_spend_by_bank: "Ranks total debit spend grouped by bank.",
  transaction_spend_by_program: "Ranks total debit spend grouped by program.",
  transaction_summary: "Combined transaction count, debit total, credit total, and net for a period.",
  largest_transaction: "The single largest transaction by amount, optionally scoped by type/date range.",
  transaction_lookup: "Looks up a single transaction by its exact reference id.",
  account_balance: "The available balance of one account, resolved by its last 4 digits.",
  financial_comparison: "Compares a metric (spend, income, or transaction count) between two periods.",
};

function Section({
  title,
  copyText,
  children,
}: {
  title: string;
  copyText?: string;
  children: ReactNode;
}) {
  return (
    <div className="space-y-1.5">
      <div className="flex items-center justify-between gap-2">
        <h4 className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">{title}</h4>
        {copyText && <CopyButton text={copyText} label={`Copy ${title.replace(/^[A-Z]\.\s*/, "").toLowerCase()}`} />}
      </div>
      {children}
    </div>
  );
}

function CodeBlock({ children }: { children: string }) {
  return (
    <pre className="max-h-72 overflow-auto rounded-xl border border-border/60 bg-muted/40 p-3 text-xs leading-relaxed">
      <code className="font-mono break-words whitespace-pre-wrap">{children}</code>
    </pre>
  );
}

/**
 * Renders the "how this answer was derived" explainability trace exactly
 * as the backend produced it - every field below is read directly from
 * `technical` (apps/api/src/response/responseFormatter.ts TechnicalTrace),
 * never reconstructed or recalculated on the frontend. The database
 * result (G) is not "sent to the LLM" - it never is; it is the input to
 * the deterministic response formatter (H), and Gemini never sees it.
 */
export function TechnicalTracePanel({ technical }: { technical: TechnicalTrace }) {
  const intentJson = JSON.stringify(technical.intent, null, 2);
  const planJson = JSON.stringify(technical.queryPlan, null, 2);
  const dbResultJson = JSON.stringify(technical.databaseResult, null, 2);
  const fullTraceJson = JSON.stringify(technical, null, 2);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-2">
        <p className="text-xs text-muted-foreground">
          A deterministic, step-by-step trace of how this answer was produced - not additional AI-generated commentary.
        </p>
        <CopyButton text={fullTraceJson} label="Copy full trace as JSON" size="xs" />
      </div>

      <Section title="A. Your question">
        <p className="rounded-xl border border-border/60 bg-muted/40 px-3 py-2 text-sm">
          {technical.userQuestion || "—"}
        </p>
      </Section>

      <Section title="B. Recognized intent">
        <p className="text-sm">
          <span className="font-mono font-medium">{technical.intentName}</span>
          {" — "}
          {INTENT_DESCRIPTIONS[technical.intentName] ?? "No description available for this intent."}
        </p>
      </Section>

      <Section title="C. Validated intent" copyText={intentJson}>
        <p className="text-xs text-muted-foreground">
          Gemini's output, after it was checked against the intent schema - the exact JSON the query planner received.
        </p>
        <CodeBlock>{intentJson}</CodeBlock>
      </Section>

      <Section title="D. Query plan" copyText={planJson}>
        <p className="text-xs text-muted-foreground">
          Built deterministically from the validated intent above - resolved bank/account ids, date windows, and the
          registered aggregation, with no SQL or free-form logic from Gemini.
        </p>
        <CodeBlock>{planJson}</CodeBlock>
      </Section>

      <Section title="E. Registered SQL template">
        <p className="text-xs text-muted-foreground">
          A fixed, pre-written parameterized query selected from the query plan's intent - never generated by Gemini.
        </p>
        <CodeBlock>{technical.sqlTemplate}</CodeBlock>
      </Section>

      <Section title="F. SQL with bound parameter values" copyText={technical.renderedSql}>
        <p className="text-xs text-muted-foreground">
          This is a safe, read-only rendering for inspection - not the execution mechanism. The database actually ran
          the template above as a parameterized statement, with these same values bound separately from the SQL text.
        </p>
        <CodeBlock>{technical.renderedSql}</CodeBlock>
      </Section>

      <Section title="G. Database query result" copyText={dbResultJson}>
        <p className="text-xs text-muted-foreground">
          The raw rows returned by PostgreSQL for the query above. This result is never shown to Gemini - it goes
          straight to the response formatter below.
        </p>
        <CodeBlock>{dbResultJson}</CodeBlock>
      </Section>

      <Section title="H. Response formatter input">
        <p className="text-xs text-muted-foreground">
          Identical to the query plan (D) and database result (G) above - the formatter receives exactly those two
          values and nothing else, so they are not duplicated here.
        </p>
      </Section>

      <Section title="I. Deterministic transformation steps">
        <ol className="space-y-1.5">
          {technical.transformationSteps.map((step, index) => (
            <li key={step.step} className="flex gap-2 text-sm">
              <span className="tabular-nums text-muted-foreground">{index + 1}.</span>
              <span>{step.description}</span>
            </li>
          ))}
        </ol>
      </Section>

      <p className="text-xs text-muted-foreground">
        The final response transformation produces exactly the answer, summary, and evidence already shown above -
        it is not repeated here.
      </p>
    </div>
  );
}
